const PageObjects = require('../pageObjects/pageObjects.page')
loginData = require('../data/data.file')
var assert = require('assert')

describe("Testing Adding Items To Cart Functionality", () => {
    it("Should add a single product to cart with user not signed in", () => {
        browser.url('/')
        PageObjects.getProducts(1).click()
        PageObjects.AddToCartButton.click()
        browser.pause(3000)
        browser.url(`${browser.options.baseUrl}/cart/`)
        
    })
    it("Should add multiple products to cart with user not signed in", () => {
        browser.url('/')
        PageObjects.getProducts(2).click()
        PageObjects.AddToCartButton.click()
        browser.pause(3000)
        browser.back()
        PageObjects.getProducts(3).click()
        PageObjects.AddToCartButton.click()
        browser.url(`${browser.options.baseUrl}/cart/`)
        browser.pause(5000)
    })
    it("Should add same product to cart multiple times with user not signed in", () => {
        browser.url('/')
        PageObjects.getProducts(4).click()
        PageObjects.AddToCartButton.click()
        browser.pause(3000)
        browser.back()
        PageObjects.getProducts(4).click()
        PageObjects.AddToCartButton.click()
        browser.url(`${browser.options.baseUrl}/cart/`)
        browser.pause(5000)
    })
    it("Add product to cart while signed in", () => {
        browser.url('/')
        PageObjects.getNavLinks(2).click()
        PageObjects.enterEmail(loginData.email)
        PageObjects.enterPassword(loginData.password)
        PageObjects.LoginButton.click()
        PageObjects.OrderContainer.waitForDisplayed()
        expect(browser).toHaveUrl('https://qw-test-store-prod.netlify.app/myaccount/') 
        browser.url('/')
        PageObjects.getProducts(1).click()
        PageObjects.AddToCartButton.click()
        browser.pause(3000)
        browser.url(`${browser.options.baseUrl}/cart/`)
        //expect(PageObjects.ProductCartPrice.getText()).to.have.text(' $325.00')
    })
    it("Ensures product is still in cart after user signs out and relogin", () => {
        browser.url('/')
        PageObjects.getNavLinks(2).click()
        PageObjects.enterEmail(loginData.email)
        PageObjects.enterPassword(loginData.password)
        PageObjects.LoginButton.click()
        PageObjects.OrderContainer.waitForDisplayed()
        expect(browser).toHaveUrl('https://qw-test-store-prod.netlify.app/myaccount/') 
        browser.url('/')
        PageObjects.getProducts(1).click()
        PageObjects.AddToCartButton.click()
        browser.pause(3000)
        browser.url(`${browser.options.baseUrl}/cart/`)
        PageObjects.getNavLinks(2).click()
        browser.url('/')
        PageObjects.getNavLinks(2).click()
        PageObjects.enterEmail(loginData.email)
        PageObjects.enterPassword(loginData.password)
        PageObjects.LoginButton.click()
        PageObjects.getNavLinks(3).click()
        assert('Multi-Vibe', PageObjects.ProductName.getText())
    })
})